<div class="row">
    <h2 class="mb-3">Produtos</h2>
</div>
<div class="row">
    <?php 
        echo $this->flashMessenger()
            ->setMessageOpenFormat('<div%s><p>')
            ->setMessageSeparatorString('</p><p>')
            ->setMessageCloseString('</p></div>')
            ->render('error', array('alert alert-block alert-danger')); 
    ?>
    <?php 
        echo $this->flashMessenger()
            ->setMessageOpenFormat('<div%s><p>')
            ->setMessageSeparatorString('</p><p>')
            ->setMessageCloseString('</p></div>')
            ->render('success', array('alert alert-success')); 
    ?>
</div>
<div class="row">
    <table class="table">
        <thead>
            <th scope="col">Nome</th>
            <th scope="col">SKU</th>
            <th scope="col">Preço</th>
            <th scope="col"></th>
            <th scope="col"></th>
        </thead>
        <tbody>
            <?php if(!isset($produtos) || count($produtos) == 0) : ?>
            <tr>
                <td colspan="5">Não existem produtos cadastrados!</td>
            </tr>
            <?php else : ?>
                <?php foreach($produtos as $p) : ?>
                    <tr>
                        <td><?= $p->getNome(); ?></td>
                        <td><?= $p->getSku(); ?></td>
                        <td><?= 'R$'.number_format($p->getPreco(), 2,",","."); ?></td>
                        <td><a href="<?php echo $this->url('produto/cadastrar',array('id'=>$p->getId())) ?>">Editar</a></td>
                        <td><a href="<?php echo $this->url('produto/excluir',array('id'=>$p->getId())) ?>">Excluir</a></td>
                    </tr>
                <?php endforeach; ?>
            <?php endif; ?>
        </tbody>
    </table>
</div>
<div class="row">
    <a class="btn btn-secondary" href="<?php echo $this->url('home') ?>">Voltar</a>
    <a class="btn btn-primary" role="button" href="<?php echo $this->url('produto/cadastrar') ?>">Novo Produto</a>
</div>